version: '3.9'

volumes:
  data_app: {}
  data_db: {}
  data_certs: {}

services:
  app:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-mgr_app
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: "mariadb"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: ${DB_USER}
      DB_MYSQL_PASSWORD: ${DB_USER_PW}
      DB_MYSQL_NAME: ${DB_NAME}
    volumes:
      - data_app:/data
      - data_certs:/etc/letsencrypt

  mariadb:
    image: jc21/mariadb-aria:latest
    container_name: nginx-proxy-mgr_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PW}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_USER_PW}
    volumes:
      - data_db:/var/lib/mysql