version: '3.9'

services:
  app:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-mgr_app
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: "mariadb"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: $DB-USER
      DB_MYSQL_PASSWORD: $DB-USER-PW
      DB_MYSQL_NAME: $DB-NAME
    volumes:
      - data_app:/data
      - data_certs:/etc/letsencrypt

  mariadb:
    image: jc21/mariadb-aria:latest
    container_name: nginx-proxy-mgr_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: $DB-ROOT-PW
      MYSQL_DATABASE: $DB-NAME
      MYSQL_USER: $DB-USER
      MYSQL_PASSWORD: $DB-USER-PW
    volumes:
      - data_db:/var/lib/mysql

volumes:
  data_app:
  data_db:
  data_certs: