version: '3.9'

volumes:
  duplicati_data:

services:
  duplicati:
    image: lscr.io/linuxserver/duplicati
    container_name: duplicati
    restart: unless-stopped
    environment:
      - PUID=0              # Create and use a custome backup-user
      - PGID=0              # Create and use a custome backup-user
      - TZ=Europe/Berlin
    volumes:
      - duplicati_data:/config
      - /var/backups:/backups
      - /:/source
    ports:
      - 8200:8200