version: '3.9'

services:
  mariadb:
    image: mariadb:latest
    container_name: wordpress_db_$NAME
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - data_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $DB-ROOT-PW
      MYSQL_DATABASE: $DB-NAME
      MYSQL_USER: $DB-USER
      MYSQL_PASSWORD: $DB-USER-PW

  redis:
    image: redis:latest
    container_name: wordpress_cache_$NAME
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - data_cache:/var/lib/redis
    environment:
      TZ: CET

  wordpress:
    image: wordpress:latest
    container_name: wordpress_app_$NAME
    restart: unless-stopped
    depends_on:
      - mariadb
    networks:
      - frontend
      - backend
    ports:
      - 127.0.0.1:8080:80
    volumes:
      - data_app:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: $DB-USER
      WORDPRESS_DB_PASSWORD: $DB-USER-PW
      WORDPRESS_DB_NAME: $DB-NAME

networks:
  frontend:
    external: true
  backend:

volumes:
  data_db:
  data_cache:
  data_app:
