version: '3.9'

networks:
  frontend:
    external: true
  backend:

volumes:
  mariadb_data:
  redis_data:
  wordpress_data:

services:
  mariadb:
    image: mariadb:latest
    container_name: wordpress_db_$NAME
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PW}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_USER_PW}

  redis:
    image: redis:latest
    container_name: wordpress_cache_$NAME
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - redis_data:/var/lib/redis
    environment:
      TZ: CET

  wordpress:
    image: wordpress:php8.1-fpm-alpine
    container_name: wordpress_app_$NAME
    restart: unless-stopped
    depends_on:
      - mariadb
    networks:
      - frontend
      - backend
    ports:
      - 127.0.0.1:8080:80
    volumes:
      - wordpress_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_USER_PW}
      WORDPRESS_DB_NAME: ${DB_NAME}