version: '3.9'

volumes:
  data: {}

services:
  portainer:
    image: portainer/portainer-ce:latest    # Image for community edition
    # image: portainer/portainer-ee:latest  # Image for enterprise
    container_name: portianer
    restart: unless-stopped
    volumes:
      - data:/data
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9443:9443/tcp
      # - 8000:8000/tcp  # Used when running K8s
    # environment:
      # - EDGE_INSECURE_POLL: 1     # Needed when using self signed cert with edge agent