version: '3.9'

volumes:
  influxdb2_data:

services:
  influxdb2:
    image: influxdb:2.2-alpine
    container_name: influxdb2
    restart: unless-stopped
    volumes:
      - influxdb2_data:/var/lib/influxdb2
      - /etc/influxdb2:/etc/influxdb2
      # - /etc/ssl/cert.pem/:/etc/ssl/cert.pem
      # - /etc/ssl/cert-key.pem/:/etc/ssl/cert-key.pem
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${ADMIN_USER}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${ADMIN_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${DB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${DB_NAME}
    #  - DOCKER_INFLUXDB_INIT_RETENTION=1w
    #  - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token
    # command: influxd --tls-cert=/etc/ssl/cert.pem --tls-key=/etc/ssl/cert-key.pem
    ports:
      - 8086:8086