version: "3.9"

volumes:
  data:
  config:

services:
  caddy:
    build: .
    pull_policy: build
    container_name: xcaddy
    restart: unless-stopped
    volumes:
      - /etc/caddy/Caddyfile:/etc/caddy/Caddyfile
      # - /etc/caddy/site:/srv  # Optional
      - data:/data
      - config:/config
    network_mode: "host"