version: '3.9'

volumes:
  uptime_data:

services:
  uptime:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: unless-stopped
    volumes:
      - uptime_data:/app/data
    ports:
      - 3001:3001

