version: '3.9'

volumes:
  data: {}
  dnsmasq: {}

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: always
    ports:
      - ${HOST_IP}:53:53/tcp
      - ${HOST_IP}:53:53/udp
      - ${HOST_IP}:67:67/udp             # Optional for DHCP
      - ${HOST_IP}:8080:80/tcp           # Change variable to 127.0.0.1 if you want to use rev. proxy on the host
    dns:
      - 127.0.0.1
      - 9.9.9.9
    volumes:
      - data:/etc/pihole
      - dnsmasq:/etc/dnsmasq.d
      - /etc/localtime:/etc/localtime:ro
    cap_add:
      - NET_ADMIN
    environment:
      ServerIP: ${HOST_IP}
      TZ: 'Europe/Berlin'
      DNS1: 9.9.9.9
      DNS2: 1.1.1.1
      WEBPASSWORD: ${WEB_PW}