version: '3.9'

networks:
  frontend:
  backend:

volumes:
  nextcloud_data:
  mariadb_data:
  redis_data:

services:
  mariadb:
    image: mariadb:10.9
    container_name: nextcloud_db_$NAME
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - backend
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    environment:
      TZ: CET
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PW}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_USER_PW}

  redis:
    image: redis:latest
    container_name: nextcloud_cache_$NAME
    restart: unless-stopped
    environment:
      TZ: CET
    command: redis-server --requirepass $REDIS-PW
    networks:
      - backend
    volumes:
      - redis_data:/var/lib/redis

  nextcloud:
    depends_on:
      - redis
      - mariadb
    image: nextcloud:stable
    container_name: nextcloud_app_$NAME
    restart: unless-stopped
    hostname: $HOSTNAME
    volumes:
      - nextcloud_data:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/zzz-custom.ini
    ports:
      - 127.0.0.1:8081:80
    networks:
      - frontend
      - backend
    environment:
      TZ: CET
      VIRTUAL_HOST: $HOSTNAME
      SMTP_HOST: ${SMTP_HOST}
      SMTP_SECURE: SSL
      SMTP_PORT: 465
      SMTP_AUTHTYPE: LOGIN
      SMTP_NAME: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_USER_PW}
      MAIL_FROM_ADDRESS: ${MAIL_FROM}
      MAIL_DOMAIN: ${MAIL_DOMAIN}
      MYSQL_HOST: mariadb
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_USER_PW}
      REDIS_HOST: redis
      REDIS_HOST_PASSWORD: ${REDIS_PW}
      NEXTCLOUD_TRUSTED_DOMAINS: ${HOSTNAME}
      TRUSTED_PROXIES: ${TRUSTED_PROXIES}