version: '3.9'

services:
  mariadb:
    image: mariadb:10.6
    container_name: nextcloud_db_$NAME
    volumes:
      - data_db:/var/lib/mysql
    networks:
      - backend
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    environment:
      TZ: CET
      MYSQL_ROOT_PASSWORD: $DB-ROOT-PW
      MYSQL_DATABASE: $DB-NAME
      MYSQL_USER: $DB-USER
      MYSQL_PASSWORD: $DB-USER-PW

  redis:
    image: redis:latest
    container_name: nextcloud_cache_$NAME
    restart: unless-stopped
    environment:
      TZ: CET
    command: redis-server --requirepass $REDIS-PW
    networks:
      - backend
    volumes:
      - data_cache:/var/lib/redis

  nextcloud:
    depends_on:
      - redis
      - mariadb
    image: nextcloud:stable
    container_name: nextcloud_app_$NAME
    restart: unless-stopped
    hostname: $HOSTNAME
    volumes:
      - data_app:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/zzz-custom.ini
    ports:
      - 127.0.0.1:8081:80
    networks:
      - frontend
      - backend
    environment:
      TZ: CET
      VIRTUAL_HOST: $HOSTNAME
      SMTP_HOST: $SMTP-HOST
      SMTP_SECURE: SSL
      SMTP_PORT: 465
      SMTP_AUTHTYPE: LOGIN
      SMTP_NAME: $SMTP_USER
      SMTP_PASSWORD: $SMTP_USER_PW
      MAIL_FROM_ADDRESS: $MAIL-FROM
      MAIL_DOMAIN: $MAIL-DOMAIN
      MYSQL_HOST: mariadb
      MYSQL_DATABASE: $DB-NAME
      MYSQL_USER: $DB-USER
      MYSQL_PASSWORD: $DB-USER-PW
      REDIS_HOST: redis
      REDIS_HOST_PASSWORD: $REDIS-PW
      NEXTCLOUD_TRUSTED_DOMAINS: $HOSTNAME
      TRUSTED_PROXIES: $TRUSTED-PROXIES

networks:
  frontend:
  backend:

volumes:
  data_app:
  data_db:
  data_cache:
