version: '3.9'

services:

  mariadb:
    image: mariadb:10.6
    container_name: nextcloud_db
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    environment:
      TZ: CET
      MYSQL_ROOT_PASSWORD: $db-root-pw
      MYSQL_DATABASE: db
      MYSQL_USER: $db-user
      MYSQL_PASSWORD: $db-user-pw

  redis:
    image: redis:latest
    container_name: nextcloud_redis
    restart: unless-stopped
    environment:
      TZ: CET
    networks:
      - backend
    volumes:
      - redis:/var/lib/redis

  nextcloud:
    depends_on:
      - redis
      - mariadb
    image: nextcloud:stable 
    container_name: nextcloud_app
    hostname: $hostname
    volumes:
      - data:/var/www/html
    ports:
      - 8180:80
    networks:
      - frontend
      - backend
    restart: unless-stopped
    environment:
      TZ: CET
      VIRTUAL_HOST: $hostname
      MYSQL_HOST: mariadb:3306
      MYSQL_DATABASE: db
      MYSQL_USER: $db-user
      MYSQL_PASSWORD: $db-user-pw
      NEXTCLOUD_TRUSTED_DOMAINS: $hostname
      TRUSTED_PROXIES: $proxy-srv-ip

networks:
  frontend:
  backend:

volumes:
  data:
  db:
  redis: